on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MINHA_KEY_DO_GITHUB }}      
      - run: npm version patch --force

