name: Bump version
on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.MINHA_KEY_DO_GITHUB }}
    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.MINHA_KEY_DO_GITHUB }}
        git-message: 'chore(release): {version}'
        preset: 'vue'
        tag-prefix: 'v'
        release-count: '10'